services:

  inquisitor:
    image: inquisitor
    container_name: inquisitor
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - inquisitor

  ftp_server:
    image: ftp_server
    container_name: ftp_server
    build:
      context: ftp_server
      dockerfile: Dockerfile
    networks:
      - inquisitor

  ftp_client:
    image: ftp_client
    container_name: ftp_client
    build:
      context: ftp_client
      dockerfile: Dockerfile
    networks:
      - inquisitor

networks:
  inquisitor:
    driver: bridge
